### ISSUE TITLE
tsr generate error when using virtual-file-routes

### ISSUE THREAD

**Issue by carriebae** [TanStack/router#2816]
### Which project does this relate to?

Router

### Describe the bug

When applying 'basic-virtual-inside-file-based' case in app in nx, tsr generate error occurs.

```
PS C:\Users\9480335\workspace\refers\nx-tanstack-router\apps\nxtest> npx tsr generate

♻️  Generating routes...
TypeError: nodes.map is not a function
    at getRouteNodesRecursive (C:\Users\9480335\workspace\refers\nx-tanstack-router\node_modules\.pnpm\@tanstack+router-generator@1.81.9\node_modules\@tanstack\router-generator\dist\cjs\filesystem\virtual\getRouteNodes.cjs:49:11)
    at Module.getRouteNodes (C:\Users\9480335\workspace\refers\nx-tanstack-router\node_modules\.pnpm\@tanstack+router-generator@1.81.9\node_modules\@tanstack\router-generator\dist\cjs\filesystem\virtual\getRouteNodes.cjs:27:26)
    at recurse (C:\Users\9480335\workspace\refers\nx-tanstack-router\node_modules\.pnpm\@tanstack+router-generator@1.81.9\node_modules\@tanstack\router-generator\dist\cjs\filesystem\physical\getRouteNodes.cjs:65:71)
    at async C:\Users\9480335\workspace\refers\nx-tanstack-router\node_modules\.pnpm\@tanstack+router-generator@1.81.9\node_modules\@tanstack\router-generator\dist\cjs\filesystem\physical\getRouteNodes.cjs:87:11
    at async Promise.all (index 1)
    at async recurse (C:\Users\9480335\workspace\refers\nx-tanstack-router\node_modules\.pnpm\@tanstack+router-generator@1.81.9\node_modules\@tanstack\router-generator\dist\cjs\filesystem\physical\getRouteNodes.cjs:82:5)
    at async Module.getRouteNodes (C:\Users\9480335\workspace\refers\nx-tanstack-router\node_modules\.pnpm\@tanstack+router-generator@1.81.9\node_modules\@tanstack\router-generator\dist\cjs\filesystem\physical\getRouteNodes.cjs:157:3)
    at async Module.generator (C:\Users\9480335\workspace\refers\nx-tanstack-router\node_modules\.pnpm\@tanstack+router-generator@1.81.9\node_modules\@tanstack\router-generator\dist\cjs\generator.cjs:66:27)
    at async Module.generate (C:\Users\9480335\workspace\refers\nx-tanstack-router\node_modules\.pnpm\@tanstack+router-cli@1.81.9\node_modules\@tanstack\router-cli\dist\cjs\generate.cjs:6:5)
    at async C:\Users\9480335\workspace\refers\nx-tanstack-router\node_modules\.pnpm\@tanstack+router-cli@1.81.9\node_modules\@tanstack\router-cli\dist\cjs\index.cjs:28:5
PS C:\Users\9480335\workspace\refers\nx-tanstack-router\apps\nxtest>
``` 

routes path (~/apps/nxtest/src/pages)
![Image](https://github.com/user-attachments/assets/3ef10a5b-77a0-4395-bd27-ea37ccb4da60)

 __virtual.ts
```typescript
import {
  defineVirtualSubtreeConfig,
  index,
  physical,
  route,
} from '@tanstack/virtual-file-routes';

// this just shows that you can use an async function to define your virtual routes
export default defineVirtualSubtreeConfig(async () => [
  index('home.tsx'),
  route('$postId', 'details.tsx'),
  physical('/inception', 'lets-go'),
]);
```

tsr.config.json
```typescript
{
    "routesDirectory": "./src/pages",
    "generatedRouteTree": "./src/routeTree.gen.ts",
    "routeFileIgnorePrefix": "-"
  }
``` 

If I ignore the posts directory, it works fine without error.

### Your Example Website or App

https://github.com/carriebae/nx-tanstack-router

### Steps to Reproduce the Bug or Issue

1. git clone https://github.com/carriebae/nx-tanstack-router
2. cd ~/nx-tanstack-router
3. pnpm i
4. cd apps/nxtest
5. npx tsr generate

### Expected behavior

tsr generate should work without errors even with __virtual.ts included.

### Platform

- OS: Windows
- Browser: Chrome
- Version: -

**Comment by davidturissini** [comment]
Also coming across this. Setting `type: "module"` in my package.json file fixes it but predictably, causes other issues. I haven't done any digging but it seems like something is being mis-translated between require and import.

**Comment by SeanCassiere** [comment]
After a bit of investigating, I've found the reason the `tsr generate` command doesn't work here is that the command exclusively uses the configuration present in the `tsr.config.json` file. As such, since your configuration file (`tsr.config.json`) does NOT have the contents of the virtual routes in the `routes` key present, your route tree wouldn't be updated with the correct routing.

The manual way of getting this to work, would be to define your virtual routes content in the `tsr.config.json` file.

@schiller-manuel any thoughts on a better approach to fixing this? Perhaps, migrating the `tsr.config.json` file to a `tsr.config.js` file?

**Comment by davidturissini** [comment]
@SeanCassiere i can also report this with vite plugin. For more context, I have my routes defined in a vite config inside of an Astro config so very possible something is going on there as well

**Comment by SeanCassiere** [comment]
@davidturissini yours will likely be dependent on where your router plugin is being called from.

---

Currently, there's a disconnect between what's in your framework config (like your `vite.config.ts`) and what's in the `tsr.config.json` file. This is what's causing the issue of the generation of the `routeTree.gen.ts` file.

The brute force fix would be to manually keep your framework config in-sync with the `tsr.config.json` file, but that's certainly far from ideal.

**Comment by chason-choate-trilliant** [comment]
Had this same issue in a repo that I could not easily enable `type: module`. But I was looking through the code and noticed you can use `__virtual.mts` (instead of `.ts`) which works as expected.
