### ISSUE TITLE
esbuild version conflict when installing @tanstack/router packages

### ISSUE THREAD

**Issue by shivam-bit** [TanStack/router#2916]
### Which project does this relate to?

Router

### Describe the bug

When attempting to install @tanstack/router-plugin and @tanstack/router-devtools as dev dependencies, the installation fails due to a version mismatch in esbuild. The installed version (0.21.5) doesn't match the expected version (0.23.1) required by the dependencies.

```
Packages: +16
Progress: resolved 502, reused 418, downloaded 6, added 16, done
node_modules/.pnpm/esbuild@0.23.1/node_modules/esbuild: Running postinstall script, failed in 188ms
.../esbuild@0.23.1/node_modules/esbuild postinstall$ node install.js
Error: Expected "0.23.1" but got "0.21.5"
    at validateBinaryVersion (/Users/shivam/genos/Little-Bird-Client/node_modules/.pnpm/esbuild@0.23.1/node_modules/esbuild/install.js:134:11)
    at /Users/shivam/test-project/node_modules/.pnpm/esbuild@0.23.1/node_modules/esbuild/install.js:284:5
```

### Your Example Website or App

NA

### Steps to Reproduce the Bug or Issue

Try running `pnpm add -D @tanstack/router-plugin @tanstack/router-devtools` in a new vite project

### Expected behavior

Should be installed without any issues

### Platform

- OS: macOS
- Browser: Chrome
- Version: latest
- Node version - 16.19.1

**Comment by shivam-bit** [comment]
Fixed by updating node version to v22
