### ISSUE TITLE
CLI Error When Using `npm create @tanstack/router@latest`

### ISSUE THREAD

**Issue by babs20** [TanStack/router#2925]
### Which project does this relate to?

Router

### Describe the bug

I am trying to use `npm create @tanstack/router@latest` to start a new project. Once I am done going through the CLI steps, it fails due to a file system error. I have tried initializing the project in an empty directory and by having the CLI create the directory.

**Example:**
```
Error: ENOENT: no such file or directory, copyfile '/home/bradyblair/.npm/_npx/cb95eaa94bb67c03/node_modules/@tanstack/create-router/templates/core/src/main.tsx' -> '/home/bradyblair/occamsec/canary-ui/src/main.tsx'
    at async copyFile (node:internal/fs/promises:620:10)
    at async Gr (file:///home/bradyblair/.npm/_npx/cb95eaa94bb67c03/node_modules/@tanstack/create-router/dist/index.mjs:44:37930)
    at async ke (file:///home/bradyblair/.npm/_npx/cb95eaa94bb67c03/node_modules/@tanstack/create-router/dist/index.mjs:44:37685)
    at async Dl (file:///home/bradyblair/.npm/_npx/cb95eaa94bb67c03/node_modules/@tanstack/create-router/dist/index.mjs:44:38166)
    at async ic (file:///home/bradyblair/.npm/_npx/cb95eaa94bb67c03/node_modules/@tanstack/create-router/dist/index.mjs:44:43867)
    at async oc (file:///home/bradyblair/.npm/_npx/cb95eaa94bb67c03/node_modules/@tanstack/create-router/dist/index.mjs:44:46521) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/home/bradyblair/.npm/_npx/cb95eaa94bb67c03/node_modules/@tanstack/create-router/templates/core/src/main.tsx',
  dest: '/home/bradyblair/occamsec/canary-ui/src/main.tsx'
}
```

### Your Example Website or App

N/A (CLI issue)

### Steps to Reproduce the Bug or Issue

1. In the terminal, run `npm create @tanstack/router@latest`
2. Go through each step. I am using the following:
    - project-name: `canary-ui` or `.`
    - bundler: `vite`
    - ide: `vscode`
    - open project: `n`
 3. Get the error message listed above.

### Expected behavior

As a user, I expected the CLI to initialize the project without error.

### Platform

- OS: Windows using WSL Ubuntu
    - WSL info: `Linux Brady-PC 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- Browser: N/A
- Version: N/A

**Comment by SeanCassiere** [comment]
This is happening on MacOS as well. Needs to be investigated.

cc @schiller-manuel

**Comment by babs20** [comment]
I believe I've found the solution to the issue. I tested it on my local environment, and it is working as expected. I've gone ahead and created a PR.
